server porth: 8084

spring:
  datasource:
    url: jdbc:h2:mem:pagosdb
    user: sa
    password:
    driver-class-name: org.h2.Driver
  

jpa:
  hibernate:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

h2:
    console:
      enabled: true
      path: /h2-console
